//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DawRevenge.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DawEntities : DbContext
    {
        public DawEntities()
            : base("name=DawEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<carro> carro { get; set; }
        public DbSet<comentario> comentario { get; set; }
        public DbSet<peticion> peticion { get; set; }
        public DbSet<ruta> ruta { get; set; }
        public DbSet<seguidorusuario> seguidorusuario { get; set; }
        public DbSet<usuario> usuario { get; set; }
    }
}
