//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DawRevenge.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class carro
    {
        public string placa { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public string marca { get; set; }
        public string modelo { get; set; }
        public string color { get; set; }
    
        public virtual usuario usuario { get; set; }
    }
}
