//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DawRevenge.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class peticion
    {
        public int id_peticion { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public Nullable<int> id_ruta { get; set; }
        public string posicionLatLon { get; set; }
        public Nullable<decimal> valor { get; set; }
        public string estado { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
    
        public virtual usuario usuario { get; set; }
        public virtual ruta ruta { get; set; }
    }
}
