//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DawRevenge.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ruta
    {
        public ruta()
        {
            this.peticion = new HashSet<peticion>();
        }
    
        public int id_ruta { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public string inicioLatLon { get; set; }
        public string finLatLon { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string estado { get; set; }
        public string nombre { get; set; }
    
        public virtual ICollection<peticion> peticion { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
