//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DawRevenge.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public usuario()
        {
            this.carro = new HashSet<carro>();
            this.comentario = new HashSet<comentario>();
            this.peticion = new HashSet<peticion>();
            this.ruta = new HashSet<ruta>();
            this.seguidorusuario = new HashSet<seguidorusuario>();
            this.seguidorusuario1 = new HashSet<seguidorusuario>();
        }
    
        public int id_usuario { get; set; }
        public string cedula { get; set; }
        public string nombres { get; set; }
        public string apellidos { get; set; }
        public string nombUsuario { get; set; }
        public string contrasenia { get; set; }
        public string matricula { get; set; }
        public string userFB { get; set; }
        public string userTW { get; set; }
        public string rutaImagen { get; set; }
        public Nullable<int> tieneCarro { get; set; }
        public Nullable<int> nMultas { get; set; }
        public Nullable<int> nSeguidores { get; set; }
        public Nullable<int> nSiguiendo { get; set; }
    
        public virtual ICollection<carro> carro { get; set; }
        public virtual ICollection<comentario> comentario { get; set; }
        public virtual ICollection<peticion> peticion { get; set; }
        public virtual ICollection<ruta> ruta { get; set; }
        public virtual ICollection<seguidorusuario> seguidorusuario { get; set; }
        public virtual ICollection<seguidorusuario> seguidorusuario1 { get; set; }
    }
}
