//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34014
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DawRevenge.EspolWS {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EspolWS.wsandroidSoap")]
    public interface wsandroidSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<string> HelloWorldAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/autenticacion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool autenticacion(string authUser, string authContrasenia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/autenticacion", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> autenticacionAsync(string authUser, string authContrasenia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/wsMateriasRegistradas", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet wsMateriasRegistradas(string codigoestudiante);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/wsMateriasRegistradas", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> wsMateriasRegistradasAsync(string codigoestudiante);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/wsMateriasDisponibles", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet wsMateriasDisponibles(string codigoestudiante);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/wsMateriasDisponibles", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> wsMateriasDisponiblesAsync(string codigoestudiante);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/wsBuscarMateria", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet wsBuscarMateria(string parametro, int tipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/wsBuscarMateria", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> wsBuscarMateriaAsync(string parametro, int tipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/wsEstudiantesRegistrados", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet wsEstudiantesRegistrados(string codigoMateria, int paralelo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/wsEstudiantesRegistrados", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> wsEstudiantesRegistradosAsync(string codigoMateria, int paralelo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/wsMateriasADictar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet wsMateriasADictar(string userprofesor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/wsMateriasADictar", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> wsMateriasADictarAsync(string userprofesor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/wsInfoparalelo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet wsInfoparalelo(string codigoMateria, int paralelo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/wsInfoparalelo", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> wsInfoparaleloAsync(string codigoMateria, int paralelo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/wsHorarioClases", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet wsHorarioClases(string codigoMateria, int paralelo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/wsHorarioClases", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> wsHorarioClasesAsync(string codigoMateria, int paralelo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/wsHorarioExamenes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet wsHorarioExamenes(string codigoMateria, int paralelo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/wsHorarioExamenes", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> wsHorarioExamenesAsync(string codigoMateria, int paralelo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/wsMateriasAulas", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet wsMateriasAulas(int idaula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/wsMateriasAulas", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> wsMateriasAulasAsync(int idaula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/wsInfoEstudiante", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet wsInfoEstudiante(string codigoEstudiante);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/wsInfoEstudiante", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> wsInfoEstudianteAsync(string codigoEstudiante);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/wsInfoEstudianteCarrera", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet wsInfoEstudianteCarrera(string codigoEstudiante);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/wsInfoEstudianteCarrera", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> wsInfoEstudianteCarreraAsync(string codigoEstudiante);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/wsInfoUsuario", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet wsInfoUsuario(string usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/wsInfoUsuario", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> wsInfoUsuarioAsync(string usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/wsInfoEstudianteGeneral", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet wsInfoEstudianteGeneral(string codestudiante);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/wsInfoEstudianteGeneral", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> wsInfoEstudianteGeneralAsync(string codestudiante);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/wsConsultaCodigoEstudiante", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet wsConsultaCodigoEstudiante(string user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/wsConsultaCodigoEstudiante", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> wsConsultaCodigoEstudianteAsync(string user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/wsActividadesExtracurriculares", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet wsActividadesExtracurriculares(string codigoestudiante);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/wsActividadesExtracurriculares", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> wsActividadesExtracurricularesAsync(string codigoestudiante);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/wsFechaRegistros", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet wsFechaRegistros();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/wsFechaRegistros", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> wsFechaRegistrosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/wsDeudasNovalor", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet wsDeudasNovalor(string matricula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/wsDeudasNovalor", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> wsDeudasNovalorAsync(string matricula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/wsDeudasvalor", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet wsDeudasvalor(string matricula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/wsDeudasvalor", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> wsDeudasvalorAsync(string matricula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/wsConsultaCalificaciones", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet wsConsultaCalificaciones(string anio, string termino, string estudiante);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/wsConsultaCalificaciones", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> wsConsultaCalificacionesAsync(string anio, string termino, string estudiante);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/wsCargaAcademicaProfesor", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet wsCargaAcademicaProfesor(int idpersona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/wsCargaAcademicaProfesor", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> wsCargaAcademicaProfesorAsync(int idpersona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/wsCargaPolitecnicaProfesor", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet wsCargaPolitecnicaProfesor(int idpersona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/wsCargaPolitecnicaProfesor", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> wsCargaPolitecnicaProfesorAsync(int idpersona);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de partes de mensaje (http://tempuri.org/xmlCarrerasCreditos.xsd) no coincide con el valor predeterminado (http://tempuri.org/).
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/wsHistorialCreditos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DawRevenge.EspolWS.wsHistorialCreditosResponse wsHistorialCreditos(DawRevenge.EspolWS.wsHistorialCreditosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/wsHistorialCreditos", ReplyAction="*")]
        System.Threading.Tasks.Task<DawRevenge.EspolWS.wsHistorialCreditosResponse> wsHistorialCreditosAsync(DawRevenge.EspolWS.wsHistorialCreditosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/wsInfoEstudianteMalla", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet wsInfoEstudianteMalla(string matricula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/wsInfoEstudianteMalla", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> wsInfoEstudianteMallaAsync(string matricula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/wsConsultaUnidadesAcademicas", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet wsConsultaUnidadesAcademicas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/wsConsultaUnidadesAcademicas", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> wsConsultaUnidadesAcademicasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/wsConsultaRoles", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet wsConsultaRoles();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/wsConsultaRoles", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> wsConsultaRolesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/wsConsultarPersonaPorNombres", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet wsConsultarPersonaPorNombres(string nombre, string apellido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/wsConsultarPersonaPorNombres", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> wsConsultarPersonaPorNombresAsync(string nombre, string apellido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/wsConsultaEstudiantePorUnidadRol", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet wsConsultaEstudiantePorUnidadRol(string idrol, string codunidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/wsConsultaEstudiantePorUnidadRol", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> wsConsultaEstudiantePorUnidadRolAsync(string idrol, string codunidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/wsConsultaProfesorPorUnidadRol", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet wsConsultaProfesorPorUnidadRol(string idrol, string codunidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/wsConsultaProfesorPorUnidadRol", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> wsConsultaProfesorPorUnidadRolAsync(string idrol, string codunidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/wsInfoPersonalEstudiante", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet wsInfoPersonalEstudiante(string matricula, string identificacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/wsInfoPersonalEstudiante", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> wsInfoPersonalEstudianteAsync(string matricula, string identificacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/wsConsultaPeriodoActual", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet wsConsultaPeriodoActual();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/wsConsultaPeriodoActual", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> wsConsultaPeriodoActualAsync();
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/xmlCarrerasCreditos.xsd")]
    public partial class wsHistorialCreditosResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoEstudianteField;
        
        private string apellidosField;
        
        private string nombresField;
        
        private string codigoDivisionField;
        
        private string codigoCarreraField;
        
        private string codigoEspecializacionField;
        
        private string nombreCarreraField;
        
        private ArrayOfEstudianteTipoCreditoTipoCredito[] creditosField;
        
        private ArrayOfEstudianteCreditoCredito[] resumenField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string CodigoEstudiante {
            get {
                return this.codigoEstudianteField;
            }
            set {
                this.codigoEstudianteField = value;
                this.RaisePropertyChanged("CodigoEstudiante");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Apellidos {
            get {
                return this.apellidosField;
            }
            set {
                this.apellidosField = value;
                this.RaisePropertyChanged("Apellidos");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Nombres {
            get {
                return this.nombresField;
            }
            set {
                this.nombresField = value;
                this.RaisePropertyChanged("Nombres");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string CodigoDivision {
            get {
                return this.codigoDivisionField;
            }
            set {
                this.codigoDivisionField = value;
                this.RaisePropertyChanged("CodigoDivision");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string CodigoCarrera {
            get {
                return this.codigoCarreraField;
            }
            set {
                this.codigoCarreraField = value;
                this.RaisePropertyChanged("CodigoCarrera");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string CodigoEspecializacion {
            get {
                return this.codigoEspecializacionField;
            }
            set {
                this.codigoEspecializacionField = value;
                this.RaisePropertyChanged("CodigoEspecializacion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string NombreCarrera {
            get {
                return this.nombreCarreraField;
            }
            set {
                this.nombreCarreraField = value;
                this.RaisePropertyChanged("NombreCarrera");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=7)]
        [System.Xml.Serialization.XmlArrayItemAttribute("TipoCredito", IsNullable=false)]
        public ArrayOfEstudianteTipoCreditoTipoCredito[] Creditos {
            get {
                return this.creditosField;
            }
            set {
                this.creditosField = value;
                this.RaisePropertyChanged("Creditos");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=8)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Credito", IsNullable=false)]
        public ArrayOfEstudianteCreditoCredito[] Resumen {
            get {
                return this.resumenField;
            }
            set {
                this.resumenField = value;
                this.RaisePropertyChanged("Resumen");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/xmlCarrerasCreditos.xsd")]
    public partial class ArrayOfEstudianteTipoCreditoTipoCredito : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idTipoCreditoField;
        
        private string nombreCreditoField;
        
        private ArrayOfEstudianteTipoCreditoMateriaMateria[] materiasCreditosField;
        
        private int totalCreditosField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int IdTipoCredito {
            get {
                return this.idTipoCreditoField;
            }
            set {
                this.idTipoCreditoField = value;
                this.RaisePropertyChanged("IdTipoCredito");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string NombreCredito {
            get {
                return this.nombreCreditoField;
            }
            set {
                this.nombreCreditoField = value;
                this.RaisePropertyChanged("NombreCredito");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Materia", IsNullable=false)]
        public ArrayOfEstudianteTipoCreditoMateriaMateria[] MateriasCreditos {
            get {
                return this.materiasCreditosField;
            }
            set {
                this.materiasCreditosField = value;
                this.RaisePropertyChanged("MateriasCreditos");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int TotalCreditos {
            get {
                return this.totalCreditosField;
            }
            set {
                this.totalCreditosField = value;
                this.RaisePropertyChanged("TotalCreditos");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/xmlCarrerasCreditos.xsd")]
    public partial class ArrayOfEstudianteTipoCreditoMateriaMateria : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoMateriaField;
        
        private string nombreMateriaField;
        
        private int numeroCreditoField;
        
        private ArrayOfEstudianteTipoCreditoMateriaMateriaEstadoMateria estadoMateriaField;
        
        private string codigoCreditoField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string CodigoMateria {
            get {
                return this.codigoMateriaField;
            }
            set {
                this.codigoMateriaField = value;
                this.RaisePropertyChanged("CodigoMateria");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string NombreMateria {
            get {
                return this.nombreMateriaField;
            }
            set {
                this.nombreMateriaField = value;
                this.RaisePropertyChanged("NombreMateria");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int NumeroCredito {
            get {
                return this.numeroCreditoField;
            }
            set {
                this.numeroCreditoField = value;
                this.RaisePropertyChanged("NumeroCredito");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public ArrayOfEstudianteTipoCreditoMateriaMateriaEstadoMateria EstadoMateria {
            get {
                return this.estadoMateriaField;
            }
            set {
                this.estadoMateriaField = value;
                this.RaisePropertyChanged("EstadoMateria");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string CodigoCredito {
            get {
                return this.codigoCreditoField;
            }
            set {
                this.codigoCreditoField = value;
                this.RaisePropertyChanged("CodigoCredito");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/xmlCarrerasCreditos.xsd")]
    public enum ArrayOfEstudianteTipoCreditoMateriaMateriaEstadoMateria {
        
        /// <comentarios/>
        APROBADA,
        
        /// <comentarios/>
        ACREDITADA,
        
        /// <comentarios/>
        CONVALIDADA,
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/xmlCarrerasCreditos.xsd")]
    public partial class ArrayOfEstudianteCreditoCredito : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string strReajusteField;
        
        private int reajusteField;
        
        private int idTipoCreditoField;
        
        private string tipoCreditoField;
        
        private int tomadosField;
        
        private int flujoField;
        
        private int excedenteField;
        
        private int excedenteParaReajusteField;
        
        private int tomadosAntesDel2013Field;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string StrReajuste {
            get {
                return this.strReajusteField;
            }
            set {
                this.strReajusteField = value;
                this.RaisePropertyChanged("StrReajuste");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Reajuste {
            get {
                return this.reajusteField;
            }
            set {
                this.reajusteField = value;
                this.RaisePropertyChanged("Reajuste");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int IdTipoCredito {
            get {
                return this.idTipoCreditoField;
            }
            set {
                this.idTipoCreditoField = value;
                this.RaisePropertyChanged("IdTipoCredito");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TipoCredito {
            get {
                return this.tipoCreditoField;
            }
            set {
                this.tipoCreditoField = value;
                this.RaisePropertyChanged("TipoCredito");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Tomados {
            get {
                return this.tomadosField;
            }
            set {
                this.tomadosField = value;
                this.RaisePropertyChanged("Tomados");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Flujo {
            get {
                return this.flujoField;
            }
            set {
                this.flujoField = value;
                this.RaisePropertyChanged("Flujo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Excedente {
            get {
                return this.excedenteField;
            }
            set {
                this.excedenteField = value;
                this.RaisePropertyChanged("Excedente");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int ExcedenteParaReajuste {
            get {
                return this.excedenteParaReajusteField;
            }
            set {
                this.excedenteParaReajusteField = value;
                this.RaisePropertyChanged("ExcedenteParaReajuste");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int TomadosAntesDel2013 {
            get {
                return this.tomadosAntesDel2013Field;
            }
            set {
                this.tomadosAntesDel2013Field = value;
                this.RaisePropertyChanged("TomadosAntesDel2013");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="wsHistorialCreditos", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class wsHistorialCreditosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string codigoEstudiante;
        
        public wsHistorialCreditosRequest() {
        }
        
        public wsHistorialCreditosRequest(string codigoEstudiante) {
            this.codigoEstudiante = codigoEstudiante;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="wsHistorialCreditosResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class wsHistorialCreditosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/xmlCarrerasCreditos.xsd", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://tempuri.org/xmlCarrerasCreditos.xsd")]
        public DawRevenge.EspolWS.wsHistorialCreditosResult wsHistorialCreditosResult;
        
        public wsHistorialCreditosResponse() {
        }
        
        public wsHistorialCreditosResponse(DawRevenge.EspolWS.wsHistorialCreditosResult wsHistorialCreditosResult) {
            this.wsHistorialCreditosResult = wsHistorialCreditosResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsandroidSoapChannel : DawRevenge.EspolWS.wsandroidSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsandroidSoapClient : System.ServiceModel.ClientBase<DawRevenge.EspolWS.wsandroidSoap>, DawRevenge.EspolWS.wsandroidSoap {
        
        public wsandroidSoapClient() {
        }
        
        public wsandroidSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsandroidSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsandroidSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsandroidSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public System.Threading.Tasks.Task<string> HelloWorldAsync() {
            return base.Channel.HelloWorldAsync();
        }
        
        public bool autenticacion(string authUser, string authContrasenia) {
            return base.Channel.autenticacion(authUser, authContrasenia);
        }
        
        public System.Threading.Tasks.Task<bool> autenticacionAsync(string authUser, string authContrasenia) {
            return base.Channel.autenticacionAsync(authUser, authContrasenia);
        }
        
        public System.Data.DataSet wsMateriasRegistradas(string codigoestudiante) {
            return base.Channel.wsMateriasRegistradas(codigoestudiante);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> wsMateriasRegistradasAsync(string codigoestudiante) {
            return base.Channel.wsMateriasRegistradasAsync(codigoestudiante);
        }
        
        public System.Data.DataSet wsMateriasDisponibles(string codigoestudiante) {
            return base.Channel.wsMateriasDisponibles(codigoestudiante);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> wsMateriasDisponiblesAsync(string codigoestudiante) {
            return base.Channel.wsMateriasDisponiblesAsync(codigoestudiante);
        }
        
        public System.Data.DataSet wsBuscarMateria(string parametro, int tipo) {
            return base.Channel.wsBuscarMateria(parametro, tipo);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> wsBuscarMateriaAsync(string parametro, int tipo) {
            return base.Channel.wsBuscarMateriaAsync(parametro, tipo);
        }
        
        public System.Data.DataSet wsEstudiantesRegistrados(string codigoMateria, int paralelo) {
            return base.Channel.wsEstudiantesRegistrados(codigoMateria, paralelo);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> wsEstudiantesRegistradosAsync(string codigoMateria, int paralelo) {
            return base.Channel.wsEstudiantesRegistradosAsync(codigoMateria, paralelo);
        }
        
        public System.Data.DataSet wsMateriasADictar(string userprofesor) {
            return base.Channel.wsMateriasADictar(userprofesor);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> wsMateriasADictarAsync(string userprofesor) {
            return base.Channel.wsMateriasADictarAsync(userprofesor);
        }
        
        public System.Data.DataSet wsInfoparalelo(string codigoMateria, int paralelo) {
            return base.Channel.wsInfoparalelo(codigoMateria, paralelo);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> wsInfoparaleloAsync(string codigoMateria, int paralelo) {
            return base.Channel.wsInfoparaleloAsync(codigoMateria, paralelo);
        }
        
        public System.Data.DataSet wsHorarioClases(string codigoMateria, int paralelo) {
            return base.Channel.wsHorarioClases(codigoMateria, paralelo);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> wsHorarioClasesAsync(string codigoMateria, int paralelo) {
            return base.Channel.wsHorarioClasesAsync(codigoMateria, paralelo);
        }
        
        public System.Data.DataSet wsHorarioExamenes(string codigoMateria, int paralelo) {
            return base.Channel.wsHorarioExamenes(codigoMateria, paralelo);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> wsHorarioExamenesAsync(string codigoMateria, int paralelo) {
            return base.Channel.wsHorarioExamenesAsync(codigoMateria, paralelo);
        }
        
        public System.Data.DataSet wsMateriasAulas(int idaula) {
            return base.Channel.wsMateriasAulas(idaula);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> wsMateriasAulasAsync(int idaula) {
            return base.Channel.wsMateriasAulasAsync(idaula);
        }
        
        public System.Data.DataSet wsInfoEstudiante(string codigoEstudiante) {
            return base.Channel.wsInfoEstudiante(codigoEstudiante);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> wsInfoEstudianteAsync(string codigoEstudiante) {
            return base.Channel.wsInfoEstudianteAsync(codigoEstudiante);
        }
        
        public System.Data.DataSet wsInfoEstudianteCarrera(string codigoEstudiante) {
            return base.Channel.wsInfoEstudianteCarrera(codigoEstudiante);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> wsInfoEstudianteCarreraAsync(string codigoEstudiante) {
            return base.Channel.wsInfoEstudianteCarreraAsync(codigoEstudiante);
        }
        
        public System.Data.DataSet wsInfoUsuario(string usuario) {
            return base.Channel.wsInfoUsuario(usuario);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> wsInfoUsuarioAsync(string usuario) {
            return base.Channel.wsInfoUsuarioAsync(usuario);
        }
        
        public System.Data.DataSet wsInfoEstudianteGeneral(string codestudiante) {
            return base.Channel.wsInfoEstudianteGeneral(codestudiante);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> wsInfoEstudianteGeneralAsync(string codestudiante) {
            return base.Channel.wsInfoEstudianteGeneralAsync(codestudiante);
        }
        
        public System.Data.DataSet wsConsultaCodigoEstudiante(string user) {
            return base.Channel.wsConsultaCodigoEstudiante(user);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> wsConsultaCodigoEstudianteAsync(string user) {
            return base.Channel.wsConsultaCodigoEstudianteAsync(user);
        }
        
        public System.Data.DataSet wsActividadesExtracurriculares(string codigoestudiante) {
            return base.Channel.wsActividadesExtracurriculares(codigoestudiante);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> wsActividadesExtracurricularesAsync(string codigoestudiante) {
            return base.Channel.wsActividadesExtracurricularesAsync(codigoestudiante);
        }
        
        public System.Data.DataSet wsFechaRegistros() {
            return base.Channel.wsFechaRegistros();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> wsFechaRegistrosAsync() {
            return base.Channel.wsFechaRegistrosAsync();
        }
        
        public System.Data.DataSet wsDeudasNovalor(string matricula) {
            return base.Channel.wsDeudasNovalor(matricula);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> wsDeudasNovalorAsync(string matricula) {
            return base.Channel.wsDeudasNovalorAsync(matricula);
        }
        
        public System.Data.DataSet wsDeudasvalor(string matricula) {
            return base.Channel.wsDeudasvalor(matricula);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> wsDeudasvalorAsync(string matricula) {
            return base.Channel.wsDeudasvalorAsync(matricula);
        }
        
        public System.Data.DataSet wsConsultaCalificaciones(string anio, string termino, string estudiante) {
            return base.Channel.wsConsultaCalificaciones(anio, termino, estudiante);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> wsConsultaCalificacionesAsync(string anio, string termino, string estudiante) {
            return base.Channel.wsConsultaCalificacionesAsync(anio, termino, estudiante);
        }
        
        public System.Data.DataSet wsCargaAcademicaProfesor(int idpersona) {
            return base.Channel.wsCargaAcademicaProfesor(idpersona);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> wsCargaAcademicaProfesorAsync(int idpersona) {
            return base.Channel.wsCargaAcademicaProfesorAsync(idpersona);
        }
        
        public System.Data.DataSet wsCargaPolitecnicaProfesor(int idpersona) {
            return base.Channel.wsCargaPolitecnicaProfesor(idpersona);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> wsCargaPolitecnicaProfesorAsync(int idpersona) {
            return base.Channel.wsCargaPolitecnicaProfesorAsync(idpersona);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DawRevenge.EspolWS.wsHistorialCreditosResponse DawRevenge.EspolWS.wsandroidSoap.wsHistorialCreditos(DawRevenge.EspolWS.wsHistorialCreditosRequest request) {
            return base.Channel.wsHistorialCreditos(request);
        }
        
        public DawRevenge.EspolWS.wsHistorialCreditosResult wsHistorialCreditos(string codigoEstudiante) {
            DawRevenge.EspolWS.wsHistorialCreditosRequest inValue = new DawRevenge.EspolWS.wsHistorialCreditosRequest();
            inValue.codigoEstudiante = codigoEstudiante;
            DawRevenge.EspolWS.wsHistorialCreditosResponse retVal = ((DawRevenge.EspolWS.wsandroidSoap)(this)).wsHistorialCreditos(inValue);
            return retVal.wsHistorialCreditosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DawRevenge.EspolWS.wsHistorialCreditosResponse> DawRevenge.EspolWS.wsandroidSoap.wsHistorialCreditosAsync(DawRevenge.EspolWS.wsHistorialCreditosRequest request) {
            return base.Channel.wsHistorialCreditosAsync(request);
        }
        
        public System.Threading.Tasks.Task<DawRevenge.EspolWS.wsHistorialCreditosResponse> wsHistorialCreditosAsync(string codigoEstudiante) {
            DawRevenge.EspolWS.wsHistorialCreditosRequest inValue = new DawRevenge.EspolWS.wsHistorialCreditosRequest();
            inValue.codigoEstudiante = codigoEstudiante;
            return ((DawRevenge.EspolWS.wsandroidSoap)(this)).wsHistorialCreditosAsync(inValue);
        }
        
        public System.Data.DataSet wsInfoEstudianteMalla(string matricula) {
            return base.Channel.wsInfoEstudianteMalla(matricula);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> wsInfoEstudianteMallaAsync(string matricula) {
            return base.Channel.wsInfoEstudianteMallaAsync(matricula);
        }
        
        public System.Data.DataSet wsConsultaUnidadesAcademicas() {
            return base.Channel.wsConsultaUnidadesAcademicas();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> wsConsultaUnidadesAcademicasAsync() {
            return base.Channel.wsConsultaUnidadesAcademicasAsync();
        }
        
        public System.Data.DataSet wsConsultaRoles() {
            return base.Channel.wsConsultaRoles();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> wsConsultaRolesAsync() {
            return base.Channel.wsConsultaRolesAsync();
        }
        
        public System.Data.DataSet wsConsultarPersonaPorNombres(string nombre, string apellido) {
            return base.Channel.wsConsultarPersonaPorNombres(nombre, apellido);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> wsConsultarPersonaPorNombresAsync(string nombre, string apellido) {
            return base.Channel.wsConsultarPersonaPorNombresAsync(nombre, apellido);
        }
        
        public System.Data.DataSet wsConsultaEstudiantePorUnidadRol(string idrol, string codunidad) {
            return base.Channel.wsConsultaEstudiantePorUnidadRol(idrol, codunidad);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> wsConsultaEstudiantePorUnidadRolAsync(string idrol, string codunidad) {
            return base.Channel.wsConsultaEstudiantePorUnidadRolAsync(idrol, codunidad);
        }
        
        public System.Data.DataSet wsConsultaProfesorPorUnidadRol(string idrol, string codunidad) {
            return base.Channel.wsConsultaProfesorPorUnidadRol(idrol, codunidad);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> wsConsultaProfesorPorUnidadRolAsync(string idrol, string codunidad) {
            return base.Channel.wsConsultaProfesorPorUnidadRolAsync(idrol, codunidad);
        }
        
        public System.Data.DataSet wsInfoPersonalEstudiante(string matricula, string identificacion) {
            return base.Channel.wsInfoPersonalEstudiante(matricula, identificacion);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> wsInfoPersonalEstudianteAsync(string matricula, string identificacion) {
            return base.Channel.wsInfoPersonalEstudianteAsync(matricula, identificacion);
        }
        
        public System.Data.DataSet wsConsultaPeriodoActual() {
            return base.Channel.wsConsultaPeriodoActual();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> wsConsultaPeriodoActualAsync() {
            return base.Channel.wsConsultaPeriodoActualAsync();
        }
    }
}
